// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqdodxjqhtfbhxcuwpcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxZG9keGpxaHRmYmh4Y3V3cGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDkzNzksImV4cCI6MjA2NTY4NTM3OX0.0ih4QV8nSqcN13-G0CxBzeHLKTEkFfKnEjKq4DvYSO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);